### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by genofire** [sebmck/ping-wrapper#1]
without words :)

**Comment by sebmck** [comment]
I don't know what the specific request is because you haven't provided any info. I'm unlikely ever going to touch this repo again so feel free to send a PR :blush:

**Comment by genofire** [comment]
I need to ping ipv6 addresses :( - is it mean, that it would be implemented?

**Comment by sebmck** [comment]
If you want it then you'll have to add it yourself, sorry.

**Comment by genofire** [comment]
okay :)
